### ISSUE TITLE
Has someone tested the DeepFace168.pickle on Multi-pie Dataset?

### ISSUE THREAD

**Issue by Rongchangle** [HRLTY/TP-GAN#10]
I tested the shared model(DeepFace168.pickle) following the setting in paper(cvpr2015, light-cnn). But the result was not good. I obtained the following result:
15°: 56.7%  
30°: 34.0%
45°: 14.7%
60°: 4.9%
Some errors may exist in my program. But I wonder if someone has tested the DeepFace168.pickle on Multi-pie Dataset?

**Comment by Rongchangle** [comment]
I found the problem. I didn't normalize the image to [0, 1]. Now i obtain a satisfying results.
0°: 100.0%
15°: 100.0%
30°: 99.7%
45°: 98.7%
60°: 88.7%
75°: 63.4%
90°: 17.4%

**Comment by Beichenxing** [comment]
您好，能否留下您的联系方式，我有许多的问题想请教

**Comment by sohey1910** [comment]
can you tell me what files of FS_aligned/，{}.csv，FS_t5pt/，FS/{}.csv are in net_input_everything_featparts.py thanks

**Comment by 994088895** [comment]
Have you see how to train and test? What files of FS_aligned/，{}.csv，FS_t5pt/，FS/{}.csv are in net_input_everything_featparts.py?   Can you tell me? Thanks! @Beichenxing @sohey1910 @Rongchangle

**Comment by xisi789** [comment]
Can you share your test code? Using TP_GAN-Mar6FS.py，the output of picture TP-GAN-MultiPIE-test-Setting2/75/201_01_01_010_08_cropped_test.png is 
![201_01_01_010_08_cropped](https://user-images.githubusercontent.com/41114558/44300022-afec6e80-a332-11e8-86e7-ec59556a0f0d.png)
@Rongchangle @HRLTY

**Comment by KevinLee752** [comment]
@xisi789 Hi, It seems you have ran this source code successfully. Would you mind sharing some instructions about getting this run as well as your platforms and python version? Thasnks :)

**Comment by HRLTY** [comment]
@xisi789  this is probably due to newly initialized weights... rather than pretrained weights.

**Comment by SilverFI** [comment]
> I found the problem. I didn't normalize the image to [0, 1] last time. After normalization i obtain a satisfying result.
> 0°: 100.0%
> 15°: 100.0%
> 30°: 99.7%
> 45°: 98.7%
> 60°: 88.7%
> 75°: 63.4%
> 90°: 17.4%

Could you share your testing method on original Multi-PIE images using deepface?
I use `samplevectors = self.samplevector.eval({self.sample_images_nocode : samples_images[ind[0]:ind[1],:,:,:],})` to get 128 dimension feature vector for each gallery image, and then for each test image, extract 128-d feature vector, calculate similarity(137*128,128*1->137*1 similarity score) and find the most similar one as prediction.  I obtained the following rank-1 result:
15: 0.48
30: 0.37
45: 0.23
60: 0.12
75: 0.06
90: 0.02
@Rongchangle @HRLTY
