### ISSUE TITLE
TP-GAN用来训练的人脸数据， 预处理的时候，使用什么工具生成人脸关键点的？

### ISSUE THREAD

**Issue by gavinsz** [HRLTY/TP-GAN#5]
def GetFeatureParts(self, img_resize, filename, label=False):
        #crop four parts
        trans_points = np.empty([5,2],dtype=np.int32)
        if True:#not label:
            featpath = self.feat5ptDir + filename[0:-15] + '_trans.5pt'

**Comment by HRLTY** [comment]
Please see updated README.
